// <auto-generated />
namespace Recipes.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _03151701 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03151701));
        
        string IMigrationMetadata.Id
        {
            get { return "201703160250230_031517-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
