// <auto-generated />
namespace Recipes.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _030817c : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_030817c));
        
        string IMigrationMetadata.Id
        {
            get { return "201703090552131_030817c"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
