// <auto-generated />
namespace Recipes.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _041817_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_041817_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201704190451027_041817_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
